using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Compiler.SymbolTable.Table
{
    public static class StandartTypes
    {
        public static (string Name, string Parent, bool IsAbstract)[] Types { get; } = new[]
        {
            ("Any", null, true),
            ("AnyVal", "Any", true),
            ("AnyRef", "Any", true),
            ("Unit", "AnyVal", false),
            ("Boolean", "AnyVal", false),
            ("Char", "AnyVal", false),
            ("Byte", "AnyVal", false),
            ("Short", "AnyVal", false),
            ("Int", "AnyVal", false),
            ("Long", "AnyVal", false),
            ("Float", "AnyVal", false),
            ("Double", "AnyVal", false),
            ("String", "AnyVal", false)
        };

        public static (string Class, (string Func, string Returns, string[] Args) Signature)[] Methods { get; } = new[]
        {
            // Boolean methods
            (Class: "Boolean", (Func: "!=", Returns: "Boolean", Args: new[] { "Boolean" })),
            (Class: "Boolean", (Func: "==", Returns: "Boolean", Args: new[] { "Boolean" })),
            (Class: "Boolean", (Func: "&&", Returns: "Boolean", Args: new[] { "Boolean" })),
            (Class: "Boolean", (Func: "||", Returns: "Boolean", Args: new[] { "Boolean" })),
            (Class: "Boolean", (Func: ">",  Returns: "Boolean", Args: new[] { "Boolean" })),
            (Class: "Boolean", (Func: ">=", Returns: "Boolean", Args: new[] { "Boolean" })),
            (Class: "Boolean", (Func: "<",  Returns: "Boolean", Args: new[] { "Boolean" })),
            (Class: "Boolean", (Func: "<=", Returns: "Boolean", Args: new[] { "Boolean" })),

            // Char methods
            (Class: "Char", (Func: "!=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Char", (Func: "!=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Char", (Func: "!=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Char", (Func: "!=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Char", (Func: "!=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Char", (Func: "!=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Char", (Func: "!=", Returns: "Boolean", Args: new[] { "Byte" })),

            (Class: "Char", (Func: "==", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Char", (Func: "==", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Char", (Func: "==", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Char", (Func: "==", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Char", (Func: "==", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Char", (Func: "==", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Char", (Func: "==", Returns: "Boolean", Args: new[] { "Byte" })),

            (Class: "Char", (Func: "<", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Char", (Func: "<", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Char", (Func: "<", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Char", (Func: "<", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Char", (Func: "<", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Char", (Func: "<", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Char", (Func: "<", Returns: "Boolean", Args: new[] { "Byte" })),

            (Class: "Char", (Func: "<=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Char", (Func: "<=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Char", (Func: "<=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Char", (Func: "<=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Char", (Func: "<=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Char", (Func: "<=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Char", (Func: "<=", Returns: "Boolean", Args: new[] { "Byte" })),

            (Class: "Char", (Func: ">", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Char", (Func: ">", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Char", (Func: ">", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Char", (Func: ">", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Char", (Func: ">", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Char", (Func: ">", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Char", (Func: ">", Returns: "Boolean", Args: new[] { "Byte" })),

            (Class: "Char", (Func: ">=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Char", (Func: ">=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Char", (Func: ">=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Char", (Func: ">=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Char", (Func: ">=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Char", (Func: ">=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Char", (Func: ">=", Returns: "Boolean", Args: new[] { "Byte" })),

            (Class: "Char", (Func: "%", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Char", (Func: "%", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Char", (Func: "%", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Char", (Func: "%", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Char", (Func: "%", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Char", (Func: "%", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Char", (Func: "%", Returns: "Int", Args: new[] { "Byte" })),

            (Class: "Char", (Func: "**", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Char", (Func: "**", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Char", (Func: "**", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Char", (Func: "**", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Char", (Func: "**", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Char", (Func: "**", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Char", (Func: "**", Returns: "Int", Args: new[] { "Byte" })),

            (Class: "Char", (Func: "++", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Char", (Func: "++", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Char", (Func: "++", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Char", (Func: "++", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Char", (Func: "++", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Char", (Func: "++", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Char", (Func: "++", Returns: "Int", Args: new[] { "Byte" })),

            (Class: "Char", (Func: "--", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Char", (Func: "--", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Char", (Func: "--", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Char", (Func: "--", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Char", (Func: "--", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Char", (Func: "--", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Char", (Func: "--", Returns: "Int", Args: new[] { "Byte" })),

            (Class: "Char", (Func: "\\", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Char", (Func: "\\", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Char", (Func: "\\", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Char", (Func: "\\", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Char", (Func: "\\", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Char", (Func: "\\", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Char", (Func: "\\", Returns: "Int", Args: new[] { "Byte" })),

            // Byte methods
            (Class: "Byte", (Func: "!=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "!=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "!=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "!=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "!=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "!=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "!=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: "==", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "==", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "==", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "==", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "==", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "==", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "==", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: "<", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "<", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "<", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "<", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "<", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "<", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "<", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: "<=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "<=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "<=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "<=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "<=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "<=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "<=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: ">", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Byte", (Func: ">", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Byte", (Func: ">", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Byte", (Func: ">", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Byte", (Func: ">", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Byte", (Func: ">", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Byte", (Func: ">", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: ">=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Byte", (Func: ">=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Byte", (Func: ">=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Byte", (Func: ">=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Byte", (Func: ">=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Byte", (Func: ">=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Byte", (Func: ">=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: "%", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "%", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "%", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "%", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "%", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "%", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "%", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: "**", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "**", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "**", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "**", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "**", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "**", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "**", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: "++", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "++", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "++", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "++", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "++", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "++", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "++", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: "--", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "--", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "--", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "--", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "--", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "--", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "--", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Byte", (Func: "\\", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Byte", (Func: "\\", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Byte", (Func: "\\", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Byte", (Func: "\\", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Byte", (Func: "\\", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Byte", (Func: "\\", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Byte", (Func: "\\", Returns: "Int", Args: new[] { "Byte" })),

            // Short methods
            (Class: "Short", (Func: "!=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Short", (Func: "!=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Short", (Func: "!=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Short", (Func: "!=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Short", (Func: "!=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Short", (Func: "!=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Short", (Func: "!=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: "==", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Short", (Func: "==", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Short", (Func: "==", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Short", (Func: "==", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Short", (Func: "==", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Short", (Func: "==", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Short", (Func: "==", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: "<", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Short", (Func: "<", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Short", (Func: "<", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Short", (Func: "<", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Short", (Func: "<", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Short", (Func: "<", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Short", (Func: "<", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: "<=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Short", (Func: "<=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Short", (Func: "<=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Short", (Func: "<=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Short", (Func: "<=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Short", (Func: "<=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Short", (Func: "<=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: ">", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Short", (Func: ">", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Short", (Func: ">", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Short", (Func: ">", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Short", (Func: ">", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Short", (Func: ">", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Short", (Func: ">", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: ">=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Short", (Func: ">=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Short", (Func: ">=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Short", (Func: ">=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Short", (Func: ">=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Short", (Func: ">=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Short", (Func: ">=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: "%", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Short", (Func: "%", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Short", (Func: "%", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Short", (Func: "%", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Short", (Func: "%", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Short", (Func: "%", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Short", (Func: "%", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: "**", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Short", (Func: "**", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Short", (Func: "**", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Short", (Func: "**", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Short", (Func: "**", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Short", (Func: "**", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Short", (Func: "**", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: "++", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Short", (Func: "++", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Short", (Func: "++", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Short", (Func: "++", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Short", (Func: "++", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Short", (Func: "++", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Short", (Func: "++", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: "--", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Short", (Func: "--", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Short", (Func: "--", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Short", (Func: "--", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Short", (Func: "--", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Short", (Func: "--", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Short", (Func: "--", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Short", (Func: "\\", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Short", (Func: "\\", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Short", (Func: "\\", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Short", (Func: "\\", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Short", (Func: "\\", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Short", (Func: "\\", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Short", (Func: "\\", Returns: "Int", Args: new[] { "Byte" })),

            // Int methods
            (Class: "Int", (Func: "!=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Int", (Func: "!=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Int", (Func: "!=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Int", (Func: "!=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Int", (Func: "!=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Int", (Func: "!=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Int", (Func: "!=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: "==", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Int", (Func: "==", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Int", (Func: "==", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Int", (Func: "==", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Int", (Func: "==", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Int", (Func: "==", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Int", (Func: "==", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: "<", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Int", (Func: "<", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Int", (Func: "<", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Int", (Func: "<", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Int", (Func: "<", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Int", (Func: "<", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Int", (Func: "<", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: "<=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Int", (Func: "<=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Int", (Func: "<=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Int", (Func: "<=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Int", (Func: "<=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Int", (Func: "<=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Int", (Func: "<=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: ">", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Int", (Func: ">", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Int", (Func: ">", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Int", (Func: ">", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Int", (Func: ">", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Int", (Func: ">", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Int", (Func: ">", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: ">=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Int", (Func: ">=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Int", (Func: ">=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Int", (Func: ">=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Int", (Func: ">=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Int", (Func: ">=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Int", (Func: ">=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: "%", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Int", (Func: "%", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Int", (Func: "%", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Int", (Func: "%", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Int", (Func: "%", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Int", (Func: "%", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Int", (Func: "%", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: "**", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Int", (Func: "**", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Int", (Func: "**", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Int", (Func: "**", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Int", (Func: "**", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Int", (Func: "**", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Int", (Func: "**", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: "++", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Int", (Func: "++", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Int", (Func: "++", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Int", (Func: "++", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Int", (Func: "++", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Int", (Func: "++", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Int", (Func: "++", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: "--", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Int", (Func: "--", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Int", (Func: "--", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Int", (Func: "--", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Int", (Func: "--", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Int", (Func: "--", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Int", (Func: "--", Returns: "Int", Args: new[] { "Byte" })),
                     
            (Class: "Int", (Func: "\\", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Int", (Func: "\\", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Int", (Func: "\\", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Int", (Func: "\\", Returns: "Int", Args: new[] { "Int" })),
            (Class: "Int", (Func: "\\", Returns: "Int", Args: new[] { "Char" })),
            (Class: "Int", (Func: "\\", Returns: "Int", Args: new[] { "Short" })),
            (Class: "Int", (Func: "\\", Returns: "Int", Args: new[] { "Byte" })),

            // Long methods
            (Class: "Long", (Func: "!=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Long", (Func: "!=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Long", (Func: "!=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Long", (Func: "!=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Long", (Func: "!=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Long", (Func: "!=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Long", (Func: "!=", Returns: "Boolean", Args: new[] { "Byte" })),
                      
            (Class: "Long", (Func: "==", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Long", (Func: "==", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Long", (Func: "==", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Long", (Func: "==", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Long", (Func: "==", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Long", (Func: "==", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Long", (Func: "==", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: "<", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Long", (Func: "<", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Long", (Func: "<", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Long", (Func: "<", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Long", (Func: "<", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Long", (Func: "<", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Long", (Func: "<", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: "<=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Long", (Func: "<=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Long", (Func: "<=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Long", (Func: "<=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Long", (Func: "<=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Long", (Func: "<=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Long", (Func: "<=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: ">", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Long", (Func: ">", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Long", (Func: ">", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Long", (Func: ">", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Long", (Func: ">", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Long", (Func: ">", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Long", (Func: ">", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: ">=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Long", (Func: ">=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Long", (Func: ">=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Long", (Func: ">=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Long", (Func: ">=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Long", (Func: ">=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Long", (Func: ">=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: "%", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Long", (Func: "%", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Long", (Func: "%", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Long", (Func: "%", Returns: "Long", Args: new[] { "Int" })),
            (Class: "Long", (Func: "%", Returns: "Long", Args: new[] { "Char" })),
            (Class: "Long", (Func: "%", Returns: "Long", Args: new[] { "Short" })),
            (Class: "Long", (Func: "%", Returns: "Long", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: "**", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Long", (Func: "**", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Long", (Func: "**", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Long", (Func: "**", Returns: "Long", Args: new[] { "Int" })),
            (Class: "Long", (Func: "**", Returns: "Long", Args: new[] { "Char" })),
            (Class: "Long", (Func: "**", Returns: "Long", Args: new[] { "Short" })),
            (Class: "Long", (Func: "**", Returns: "Long", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: "++", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Long", (Func: "++", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Long", (Func: "++", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Long", (Func: "++", Returns: "Long", Args: new[] { "Int" })),
            (Class: "Long", (Func: "++", Returns: "Long", Args: new[] { "Char" })),
            (Class: "Long", (Func: "++", Returns: "Long", Args: new[] { "Short" })),
            (Class: "Long", (Func: "++", Returns: "Long", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: "--", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Long", (Func: "--", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Long", (Func: "--", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Long", (Func: "--", Returns: "Long", Args: new[] { "Int" })),
            (Class: "Long", (Func: "--", Returns: "Long", Args: new[] { "Char" })),
            (Class: "Long", (Func: "--", Returns: "Long", Args: new[] { "Short" })),
            (Class: "Long", (Func: "--", Returns: "Long", Args: new[] { "Byte" })),
                     
            (Class: "Long", (Func: "\\", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Long", (Func: "\\", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Long", (Func: "\\", Returns: "Long", Args: new[] { "Long" })),
            (Class: "Long", (Func: "\\", Returns: "Long", Args: new[] { "Int" })),
            (Class: "Long", (Func: "\\", Returns: "Long", Args: new[] { "Char" })),
            (Class: "Long", (Func: "\\", Returns: "Long", Args: new[] { "Short" })),
            (Class: "Long", (Func: "\\", Returns: "Long", Args: new[] { "Byte" })),

            // Float methods
            (Class: "Float", (Func: "!=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Float", (Func: "!=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Float", (Func: "!=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Float", (Func: "!=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Float", (Func: "!=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Float", (Func: "!=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Float", (Func: "!=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: "==", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Float", (Func: "==", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Float", (Func: "==", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Float", (Func: "==", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Float", (Func: "==", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Float", (Func: "==", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Float", (Func: "==", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: "<", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Float", (Func: "<", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Float", (Func: "<", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Float", (Func: "<", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Float", (Func: "<", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Float", (Func: "<", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Float", (Func: "<", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: "<=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Float", (Func: "<=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Float", (Func: "<=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Float", (Func: "<=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Float", (Func: "<=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Float", (Func: "<=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Float", (Func: "<=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: ">", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Float", (Func: ">", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Float", (Func: ">", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Float", (Func: ">", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Float", (Func: ">", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Float", (Func: ">", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Float", (Func: ">", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: ">=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Float", (Func: ">=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Float", (Func: ">=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Float", (Func: ">=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Float", (Func: ">=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Float", (Func: ">=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Float", (Func: ">=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: "%", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Float", (Func: "%", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Float", (Func: "%", Returns: "Float", Args: new[] { "Long" })),
            (Class: "Float", (Func: "%", Returns: "Float", Args: new[] { "Int" })),
            (Class: "Float", (Func: "%", Returns: "Float", Args: new[] { "Char" })),
            (Class: "Float", (Func: "%", Returns: "Float", Args: new[] { "Short" })),
            (Class: "Float", (Func: "%", Returns: "Float", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: "**", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Float", (Func: "**", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Float", (Func: "**", Returns: "Float", Args: new[] { "Long" })),
            (Class: "Float", (Func: "**", Returns: "Float", Args: new[] { "Int" })),
            (Class: "Float", (Func: "**", Returns: "Float", Args: new[] { "Char" })),
            (Class: "Float", (Func: "**", Returns: "Float", Args: new[] { "Short" })),
            (Class: "Float", (Func: "**", Returns: "Float", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: "++", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Float", (Func: "++", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Float", (Func: "++", Returns: "Float", Args: new[] { "Long" })),
            (Class: "Float", (Func: "++", Returns: "Float", Args: new[] { "Int" })),
            (Class: "Float", (Func: "++", Returns: "Float", Args: new[] { "Char" })),
            (Class: "Float", (Func: "++", Returns: "Float", Args: new[] { "Short" })),
            (Class: "Float", (Func: "++", Returns: "Float", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: "--", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Float", (Func: "--", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Float", (Func: "--", Returns: "Float", Args: new[] { "Long" })),
            (Class: "Float", (Func: "--", Returns: "Float", Args: new[] { "Int" })),
            (Class: "Float", (Func: "--", Returns: "Float", Args: new[] { "Char" })),
            (Class: "Float", (Func: "--", Returns: "Float", Args: new[] { "Short" })),
            (Class: "Float", (Func: "--", Returns: "Float", Args: new[] { "Byte" })),
                     
            (Class: "Float", (Func: "\\", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Float", (Func: "\\", Returns: "Float", Args: new[] { "Float" })),
            (Class: "Float", (Func: "\\", Returns: "Float", Args: new[] { "Long" })),
            (Class: "Float", (Func: "\\", Returns: "Float", Args: new[] { "Int" })),
            (Class: "Float", (Func: "\\", Returns: "Float", Args: new[] { "Char" })),
            (Class: "Float", (Func: "\\", Returns: "Float", Args: new[] { "Short" })),
            (Class: "Float", (Func: "\\", Returns: "Float", Args: new[] { "Byte" })),

            // Double methods
            (Class: "Double", (Func: "!=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Double", (Func: "!=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Double", (Func: "!=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Double", (Func: "!=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Double", (Func: "!=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Double", (Func: "!=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Double", (Func: "!=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: "==", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Double", (Func: "==", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Double", (Func: "==", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Double", (Func: "==", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Double", (Func: "==", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Double", (Func: "==", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Double", (Func: "==", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: "<", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Double", (Func: "<", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Double", (Func: "<", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Double", (Func: "<", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Double", (Func: "<", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Double", (Func: "<", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Double", (Func: "<", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: "<=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Double", (Func: "<=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Double", (Func: "<=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Double", (Func: "<=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Double", (Func: "<=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Double", (Func: "<=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Double", (Func: "<=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: ">", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Double", (Func: ">", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Double", (Func: ">", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Double", (Func: ">", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Double", (Func: ">", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Double", (Func: ">", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Double", (Func: ">", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: ">=", Returns: "Boolean", Args: new[] { "Double" })),
            (Class: "Double", (Func: ">=", Returns: "Boolean", Args: new[] { "Float" })),
            (Class: "Double", (Func: ">=", Returns: "Boolean", Args: new[] { "Long" })),
            (Class: "Double", (Func: ">=", Returns: "Boolean", Args: new[] { "Int" })),
            (Class: "Double", (Func: ">=", Returns: "Boolean", Args: new[] { "Char" })),
            (Class: "Double", (Func: ">=", Returns: "Boolean", Args: new[] { "Short" })),
            (Class: "Double", (Func: ">=", Returns: "Boolean", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: "%", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Double", (Func: "%", Returns: "Double", Args: new[] { "Float" })),
            (Class: "Double", (Func: "%", Returns: "Double", Args: new[] { "Long" })),
            (Class: "Double", (Func: "%", Returns: "Double", Args: new[] { "Int" })),
            (Class: "Double", (Func: "%", Returns: "Double", Args: new[] { "Char" })),
            (Class: "Double", (Func: "%", Returns: "Double", Args: new[] { "Short" })),
            (Class: "Double", (Func: "%", Returns: "Double", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: "**", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Double", (Func: "**", Returns: "Double", Args: new[] { "Float" })),
            (Class: "Double", (Func: "**", Returns: "Double", Args: new[] { "Long" })),
            (Class: "Double", (Func: "**", Returns: "Double", Args: new[] { "Int" })),
            (Class: "Double", (Func: "**", Returns: "Double", Args: new[] { "Char" })),
            (Class: "Double", (Func: "**", Returns: "Double", Args: new[] { "Short" })),
            (Class: "Double", (Func: "**", Returns: "Double", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: "++", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Double", (Func: "++", Returns: "Double", Args: new[] { "Float" })),
            (Class: "Double", (Func: "++", Returns: "Double", Args: new[] { "Long" })),
            (Class: "Double", (Func: "++", Returns: "Double", Args: new[] { "Int" })),
            (Class: "Double", (Func: "++", Returns: "Double", Args: new[] { "Char" })),
            (Class: "Double", (Func: "++", Returns: "Double", Args: new[] { "Short" })),
            (Class: "Double", (Func: "++", Returns: "Double", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: "--", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Double", (Func: "--", Returns: "Double", Args: new[] { "Float" })),
            (Class: "Double", (Func: "--", Returns: "Double", Args: new[] { "Long" })),
            (Class: "Double", (Func: "--", Returns: "Double", Args: new[] { "Int" })),
            (Class: "Double", (Func: "--", Returns: "Double", Args: new[] { "Char" })),
            (Class: "Double", (Func: "--", Returns: "Double", Args: new[] { "Short" })),
            (Class: "Double", (Func: "--", Returns: "Double", Args: new[] { "Byte" })),
                     
            (Class: "Double", (Func: "\\", Returns: "Double", Args: new[] { "Double" })),
            (Class: "Double", (Func: "\\", Returns: "Double", Args: new[] { "Float" })),
            (Class: "Double", (Func: "\\", Returns: "Double", Args: new[] { "Long" })),
            (Class: "Double", (Func: "\\", Returns: "Double", Args: new[] { "Int" })),
            (Class: "Double", (Func: "\\", Returns: "Double", Args: new[] { "Char" })),
            (Class: "Double", (Func: "\\", Returns: "Double", Args: new[] { "Short" })),
            (Class: "Double", (Func: "\\", Returns: "Double", Args: new[] { "Byte" })),
        };
    }
}
